name: Update VSCode

on:
  schedule:
    # Run daily at UTC 22:30 (JST 7:30)
    - cron: '30 22 * * *'
  workflow_dispatch: # Manual execution allowed

jobs:
  update:
    uses: ./.github/workflows/_update-vscode-template.yml
    with:
      edition: stable
      package_path: pkgs/vscode/default.nix
      package_name: vscode
      api_channel: stable
      display_name: VSCode
